#/etc/docker/prometheus.yml
global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'prometheus'
scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: 
        - 'h-00000004.eu-c-1.cloud.plus4u.net:8080'
        - 'h-00000005.eu-c-1.cloud.plus4u.net:8080'
        - 'h-00000006.eu-c-1.cloud.plus4u.net:8080'
        - 'h-00000007.eu-c-1.cloud.plus4u.net:8080'
        - 'h-00000008.eu-c-1.cloud.plus4u.net:8080'
        - 'h-00000009.eu-c-1.cloud.plus4u.net:8080'
        - 'h-00000010.eu-c-1.cloud.plus4u.net:8080'
        - 'h-00000011.eu-c-1.cloud.plus4u.net:8080'
        - 'h-00000012.eu-c-1.cloud.plus4u.net:8080'
