#/etc/docker/docker-compose.yml 
version: '3.4'
services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    network_mode: "bridge"
    volumes:
      - grafana_data:/var/lib/grafana
      - /etc/docker/grafana/datasources:/etc/grafana/datasources
      - /etc/docker/grafana/dashboards:/etc/grafana/dashboards
      - /etc/docker/grafana/setup.sh:/setup.sh
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    entrypoint: /setup.sh
    ports:
      - 3000:3000
    restart: always
volumes:
    grafana_data: {}
