#/etc/docker/docker-compose.yml
version: '3.4'
services:
  cadvisor:
    ports:
      - 8080:8080
    image: google/cadvisor:latest
    hostname: '{{.Node.Hostname}}'
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /etc/localtime:/etc/localtime:ro
    deploy:
      mode: global
